// AUTO-GENERATED by scripts/port-pspf-data.mjs — do not edit by hand.

import type { Domain, Requirement, RequirementId } from '../data/types.ts';
import { governanceDomain, governanceRequirements } from './governance.ts';
import { informationDomain, informationRequirements } from './information.ts';
import { personnelDomain, personnelRequirements } from './personnel.ts';
import { physicalDomain, physicalRequirements } from './physical.ts';
import { riskDomain, riskRequirements } from './risk.ts';
import { technologyDomain, technologyRequirements } from './technology.ts';
import { essentialEightControls } from './essential-eight.ts';

export const allDomains: readonly Domain[] = [
  governanceDomain,
  informationDomain,
  personnelDomain,
  physicalDomain,
  riskDomain,
  technologyDomain,
];

export const allRequirements: readonly Requirement[] = [
  ...governanceRequirements,
  ...informationRequirements,
  ...personnelRequirements,
  ...physicalRequirements,
  ...riskRequirements,
  ...technologyRequirements,
];

export const requirementById: ReadonlyMap<RequirementId, Requirement> = new Map(
  allRequirements.map((r) => [r.id, r]),
);

export const requirementsByDomain: ReadonlyMap<string, readonly Requirement[]> = new Map(
  allDomains.map((d) => [d.key, allRequirements.filter((r) => r.domain === d.key)]),
);

export type { Domain, Requirement, EssentialEightControl } from '../data/types.ts';
export { essentialEightControls };
