// AUTO-GENERATED by scripts/port-pspf-data.mjs — do not edit by hand.
// Re-run after updating PSPF source data.

import type { Domain, Requirement } from '../data/types.ts';
import { asRequirementId } from '../data/types.ts';

export const physicalDomain: Domain = {
  key: 'physical',
  name: 'Physical Security',
  description:
    'Security planning for facilities, certification and accreditation of physical assets, access controls, and technical surveillance measures.',
  prefixes: ['PHYS'],
};

export const physicalRequirements: readonly Requirement[] = [
  {
    id: asRequirementId('PHYS-189'),
    domain: 'physical',
    title: `Protective security is integrated in the process of planning, sel...`,
    text: `Protective security is integrated in the process of planning, selecting, designing and modifying entity facilities for the protection of people, information and resources.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-190'),
    domain: 'physical',
    title: `A facility security plan is developed for new facilities, facilit...`,
    text: `A facility security plan is developed for new facilities, facilities under construction or major refurbishments of existing facilities.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-191'),
    domain: 'physical',
    title: `Decisions on entity facility locations are informed by considerin...`,
    text: `Decisions on entity facility locations are informed by considering the site selection factors for Australian Government facilities.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-192'),
    domain: 'physical',
    title: `When designing or modifying facilities, the entity secures and co...`,
    text: `When designing or modifying facilities, the entity secures and controls access to facilities to meet the highest risk level to entity resources in accordance with Security Zone restricted access definitions.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-193'),
    domain: 'physical',
    title: `Facilities are constructed in accordance the applicable ASIO Tech...`,
    text: `Facilities are constructed in accordance the applicable ASIO Technical Notes to protect against the highest risk level in accordance with the entity security risk assessment in areas: accessed by the public and authorised personnel, and where physical resources and technical assets, other than security classified resources and technology, are stored.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-194'),
    domain: 'physical',
    title: `Facilities for Security Zones Two to Five that process, store or ...`,
    text: `Facilities for Security Zones Two to Five that process, store or communicate security classified information and resources are constructed in accordance with the applicable sections of ASIO Technical Note 1/15 – Physical Security Zones, and ASIO Technical Note 5/12 – Physical Security Zones (TOP SECRET) areas.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-195'),
    domain: 'physical',
    title: `Entity facilities are operated and maintained in accordance with ...`,
    text: `Entity facilities are operated and maintained in accordance with Security Zones and Physical Security Measures and Controls.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-196'),
    domain: 'physical',
    title: `Security Zones One to Four are certified by the Certification Aut...`,
    text: `Security Zones One to Four are certified by the Certification Authority in accordance with the PSPF and applicable ASIO Technical Notes before they are used operationally.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-197'),
    domain: 'physical',
    title: `Security Zone Five areas that contain TOP SECRET security classif...`,
    text: `Security Zone Five areas that contain TOP SECRET security classified information or aggregated information where the compromise of confidentiality, loss of integrity or unavailability of that information may have a catastrophic business impact level, are certified by ASIO-T4 before they are used operationally.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-198'),
    domain: 'physical',
    title: `Security Zones One to Five are accredited by the Accreditation Au...`,
    text: `Security Zones One to Five are accredited by the Accreditation Authority before they are used operationally, on the basis that the required security controls are certified and the entity determines and accepts the residual risks.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-199'),
    domain: 'physical',
    title: `Sensitive Compartmented Information Facility areas used to secure...`,
    text: `Sensitive Compartmented Information Facility areas used to secure and access TOP SECRET systems and security classified compartmented information are accredited by the Australian Signals Directorate before they are used operationally.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-200'),
    domain: 'physical',
    title: `Physical security measures are implemented to minimise or remove ...`,
    text: `Physical security measures are implemented to minimise or remove the risk of information and physical asset resources being made inoperable or inaccessible, or being accessed, used or removed without appropriate authorisation.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-201'),
    domain: 'physical',
    title: `Physical security measures are implemented to protect entity reso...`,
    text: `Physical security measures are implemented to protect entity resources, commensurate with the assessed business impact level of their compromise, loss or damage.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-202'),
    domain: 'physical',
    title: `Physical security measures are implemented to minimise or remove ...`,
    text: `Physical security measures are implemented to minimise or remove the risk of harm to people.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-203'),
    domain: 'physical',
    title: `The appropriate container, safe, vault, cabinet, secure room or s...`,
    text: `The appropriate container, safe, vault, cabinet, secure room or strong rooms is used to protect entity information and resources based on the applicable Security Zone and business impact level of the compromise, loss or damage to information or physical resources.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-204'),
    domain: 'physical',
    title: `Perimeter doors and hardware in areas that process, store or comm...`,
    text: `Perimeter doors and hardware in areas that process, store or communicate security classified information or resources are constructed and secured in accordance with the physical security measures and controls for perimeter doors and hardware.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-205'),
    domain: 'physical',
    title: `Access by authorised personnel, vehicles and equipment to Securit...`,
    text: `Access by authorised personnel, vehicles and equipment to Security Zones One to Five is controlled in accordance with the physical security measures and controls for access control for authorised personnel.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-206'),
    domain: 'physical',
    title: `Access by visitors to Security Zones One to Five is controlled in...`,
    text: `Access by visitors to Security Zones One to Five is controlled in accordance with the physical security measures and controls for access control for visitors.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-207'),
    domain: 'physical',
    title: `The Accountable Authority or Chief Security Officer approves ongo...`,
    text: `The Accountable Authority or Chief Security Officer approves ongoing (or regular) access to entity facilities for people who are not directly engaged by the entity or covered by the terms of a contract or agreement, on the basis that the person: has the required security clearance level for the Security Zone/s, and a business need supported by a business case and security risk assessment, which is reassessed at least every two years.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-208'),
    domain: 'physical',
    title: `Unauthorised access to Security Zones One to Five is controlled i...`,
    text: `Unauthorised access to Security Zones One to Five is controlled in accordance with the physical security measures and controls for security alarm systems.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-209'),
    domain: 'physical',
    title: `Security guard arrangements in Security Zones One to Five are est...`,
    text: `Security guard arrangements in Security Zones One to Five are established in accordance with the physical security measures and controls for security guards.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('PHYS-210'),
    domain: 'physical',
    title: `Technical surveillance countermeasures for Security Zones One to ...`,
    text: `Technical surveillance countermeasures for Security Zones One to Five are established in accordance with the physical security measures and controls for technical surveillance countermeasures.`,
    reportingType: 'unspecified',
  },
];
