// AUTO-GENERATED by scripts/port-pspf-data.mjs — do not edit by hand.
// Re-run after updating PSPF source data.

import type { Domain, Requirement } from '../data/types.ts';
import { asRequirementId } from '../data/types.ts';

export const riskDomain: Domain = {
  key: 'risk',
  name: 'Risk Management',
  description:
    'Security risk management aligned with enterprise risk, including third-party, supply chain, and foreign interference risk management.',
  prefixes: ['RISK'],
};

export const riskRequirements: readonly Requirement[] = [
  {
    id: asRequirementId('RISK-036'),
    domain: 'risk',
    title: `The Accountable Authority determines their entity's tolerance for security ri...`,
    text: `The Accountable Authority determines their entity's tolerance for security risks and documents in the security plan.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-037'),
    domain: 'risk',
    title: `A risk steward (or manager) is identified for each security risk or category ...`,
    text: `A risk steward (or manager) is identified for each security risk or category of security risk, including shared risks.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-038'),
    domain: 'risk',
    title: `The Accountable Authority considers the impact that their security risk manag...`,
    text: `The Accountable Authority considers the impact that their security risk management decisions could potentially have on other entities, and shares information on risks where appropriate.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-039'),
    domain: 'risk',
    title: `The entity is accountable for the management of security risks arising from p...`,
    text: `The entity is accountable for the management of security risks arising from procuring goods and services and ensures procurement and contract decisions do not expose the entity or the Australian Government to an unacceptable level of risk.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-040'),
    domain: 'risk',
    title: `Procurement, contracts and third-party outsourced arrangements contain propor...`,
    text: `Procurement, contracts and third-party outsourced arrangements contain proportionate security terms and conditions to ensure service providers, contractors and subcontractors comply with relevant PSPF Requirements and avoid exposing the entity or the Australian Government to an unacceptable level of risk.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-041'),
    domain: 'risk',
    title: `Entity ensures service providers, contractors and subcontractors comply with ...`,
    text: `Entity ensures service providers, contractors and subcontractors comply with relevant PSPF Requirements as detailed by the entity.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-042'),
    domain: 'risk',
    title: `Contractual security terms and conditions require service providers to report...`,
    text: `Contractual security terms and conditions require service providers to report any actual or suspected security incidents to the entity, and follow reasonable direction from the entity arising from incident investigations.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-043'),
    domain: 'risk',
    title: `Government entities providing outsourced services provide IRAP assessment rep...`,
    text: `Government entities providing outsourced services provide IRAP assessment reports to the government entities consuming, or looking to consume, their services.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-044'),
    domain: 'risk',
    title: `Contract security terms and conditions are monitored and reviewed to ensure t...`,
    text: `Contract security terms and conditions are monitored and reviewed to ensure the specified security controls, terms and conditions are implemented, operated and maintained by the contracted provider, including any subcontractors, over the life of a contract.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-045'),
    domain: 'risk',
    title: `Contractual terms and conditions include appropriate security arrangements fo...`,
    text: `Contractual terms and conditions include appropriate security arrangements for the completion or termination of the contract.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-046'),
    domain: 'risk',
    title: `Procurement and contract decisions consider the security risks before engagin...`,
    text: `Procurement and contract decisions consider the security risks before engaging providers operating under foreign ownership, control or influence, and in response to any developments during the contract period that may give rise to foreign ownership, control or influence risks.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-047'),
    domain: 'risk',
    title: `Security risks arising from contractual arrangements for the provision of goo...`,
    text: `Security risks arising from contractual arrangements for the provision of goods and services are managed, reassessed and adjusted over the life of a contract.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-048'),
    domain: 'risk',
    title: `Secure and verifiable third-party vendors, providers, partners and associated...`,
    text: `Secure and verifiable third-party vendors, providers, partners and associated services are used unless business operations require use, and the residual risks are managed and approved by the Chief Information Security Officer`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-049'),
    domain: 'risk',
    title: `Entities manage the security risks associated with engaging with foreign part...`,
    text: `Entities manage the security risks associated with engaging with foreign partners.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-050'),
    domain: 'risk',
    title: `Personnel do not publicise their security clearance level on social media pla...`,
    text: `Personnel do not publicise their security clearance level on social media platforms, including employment-focused platforms such as LinkedIn.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-051'),
    domain: 'risk',
    title: `Insider Threat program...`,
    text: `An insider threat program is implemented by entities that manage Baseline to Positive Vetting security clearance subjects, to manage the risk of insider threat in the entity.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-052'),
    domain: 'risk',
    title: `Exceptional circumstances and risk tolerance...`,
    text: `Where exceptional circumstances prevent or affect an entity's capability to implement a PSPF requirement or standard, the Accountable Authority may vary application, for a limited period of time, consistent with the entity's risk tolerance.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-053'),
    domain: 'risk',
    title: `Exceptional circumstance decisions are recorded in the plan...`,
    text: `Decisions to vary implementation of a PSPF requirement or standard due to exceptional circumstances are documented in the entity's security plan.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-054'),
    domain: 'risk',
    title: `Alternative mitigations are reviewed annually`,
    text: `Decisions to implement an alternative mitigation measure that meets or exceeds a PSPF requirement or standard are reviewed and reported annually.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-055'),
    domain: 'risk',
    title: `Business Continuity Plan is developed...`,
    text: `A business continuity plan is developed, implemented and maintained to respond effectively and minimise the impacts of significant business disruptions to the entity's critical services and assets, and other services and assets when warranted by a threat and security risk assessment.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-056'),
    domain: 'risk',
    title: `Emergency planning is in BCP...`,
    text: `Plans for managing a broad range of emergencies are integrated within the business continuity plan.`,
    reportingType: 'unspecified',
  },
  {
    id: asRequirementId('RISK-057'),
    domain: 'risk',
    title: `Emergency notifications...`,
    text: `Personnel who are likely to be impacted are notified if there is a heightened risk of an emergency.`,
    reportingType: 'unspecified',
  },
];
